# Copyright (c) 2019 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-annotate-webhook
  labels:
    app: pod-annotate-webhook
spec:
  selector:
    matchLabels:
      app: pod-annotate-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-annotate-webhook
    spec:
      containers:
        - name: pod-annotate-webhook
          image: quay.io/snir/kata-webhook-example:latest
          imagePullPolicy: Always
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-key-file=/etc/webhook/certs/key.pem
            - -exclude-namespaces=rook-ceph-system,rook-ceph
#            - -regex-namespaces=^e2e-.* # for example, this regex string will apply only on the e2e testing suite namespaces
#            - -mutate-where-installed # if set pods will be mutated only on the namespace where webhook is deployed, mutual exlusive with regex-namespaces
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: webhook-certs
          secret:
            secretName: pod-annotate-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: pod-annotate-webhook
  labels:
    app: pod-annotate-webhook
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: pod-annotate-webhook
